"""
Layer 0: Static curated company list — always-on, never blocked.

WHY THIS EXISTS
---------------
Job board scrapers (Indeed, LinkedIn, Dice, Naukri, StepStone, etc.) are fragile:
  - Cloudflare bot detection blocks headless/automated requests
  - JavaScript-rendered pages return empty HTML to plain requests
  - Rate limits and IP bans silently return 0 results
  - APIs change or require auth (Dice changed endpoint, LinkedIn deprecated API)

This file contains 300+ companies that are hardcoded because:
  1. They ALWAYS hire data / AI / ML engineers — no discovery needed
  2. This layer seeds master_employers.csv reliably on EVERY run
  3. It's the foundation; job board scraping is additive bonus on top

COVERAGE
--------
  - FAANG + US Big Tech              (40 companies)
  - US AI / Data / MLOps Specialists (35 companies)
  - US Mid-tier Tech                 (20 companies)
  - EU MNCs — Germany, NL, Sweden    (30 companies)
  - EU Tech Leaders by country       (35 companies)
  - India Top Employers — MNCs       (20 companies)
  - India Product / Unicorns         (25 companies)
  - Japan Big Tech                   (20 companies)
  - AU / NZ Leaders                  (25 companies)
  - Global Remote-First              (15 companies)

USAGE
-----
    from static_companies import load_static_companies
    rows = load_static_companies()   # list of dicts matching FIELDS in schema.py
"""

from datetime import datetime

_TODAY = datetime.today().strftime("%Y-%m-%d")

_EU_BLUE_CARD_COUNTRIES = {
    "Germany", "Netherlands", "France", "Sweden", "Spain", "Portugal",
    "Denmark", "Finland", "Austria", "Belgium", "Poland", "Czech Republic",
    "Ireland", "Switzerland", "Norway", "Estonia", "Latvia", "Lithuania",
    "Hungary", "Croatia", "Slovakia", "Bulgaria", "Greece", "Luxembourg",
    "Italy", "Romania",
}


def _co(
    name, website, country,
    sector="Tech / AI / Data",
    stage="Unknown",
    category="",
    tech="",
    reason="",
    visa="yes",
    lang="English",
    remote="Unknown",
    geo="",
    careers="",
    scale="Unknown",
):
    """Build a full schema-compatible dict with sensible defaults."""
    eligibility = "Eligible" if country in _EU_BLUE_CARD_COUNTRIES else "Research needed"
    return {
        "Company":               name,
        "Website":               website,
        "Careers_URL":           careers or f"https://{website}/careers",
        "Country":               country,
        "City":                  "Unknown",
        "Sector":                sector,
        "Subsector":             "",
        "Company_Stage":         stage,
        "Company_Scale":         scale,
        "Employer_Category":     category or "static_list",
        "Remote":                remote,
        "Visa_Sponsorship":      visa,
        "EOR":                   "Unknown",
        "Hiring_Geography":      geo or country,
        "Target_Roles":          "Data Engineer / ML Engineer / AI Engineer",
        "Tech_Stack":            tech,
        "Region_Eligibility":    eligibility,
        "Portfolio_Theme_Match": "",
        "Language_Requirement":  lang,
        "Hiring_Confidence":     "High",
        "Reason_Match":          reason or f"Top employer in {country} — always hires data/AI engineers",
        "Source":                "static_list",
        "Cold_Outreach_Candidate": "",
        "Visa_Sponsor_Register": "Unknown",
    }


# ─────────────────────────────────────────────────────────────
#  US BIG TECH — FAANG + TIER 1  (40 companies)
# ─────────────────────────────────────────────────────────────
US_BIG_TECH = [
    _co("Google", "google.com", "USA",
        sector="AI / Cloud / Search", stage="Public", category="faang",
        tech="Python, TensorFlow, BigQuery, Kubernetes, Go",
        reason="Global AI leader — hundreds of data engineer roles across EU, US, India offices",
        visa="yes", remote="Hybrid", scale="100000+"),
    _co("Meta", "meta.com", "USA",
        sector="AI / Social / AR", stage="Public", category="faang",
        tech="Python, PyTorch, Spark, Hive, Presto, Hack",
        reason="Massive AI/ML investment — data engineering is core to Meta's entire stack",
        visa="yes", remote="Hybrid", scale="50000+"),
    _co("Amazon", "amazon.com", "USA",
        sector="Cloud / E-Commerce / AI", stage="Public", category="faang",
        tech="Python, AWS, Spark, Redshift, Glue, SageMaker",
        reason="AWS alone hires thousands of data engineers globally; EU offices in Dublin, Berlin, Luxembourg",
        visa="yes", remote="Hybrid", scale="100000+"),
    _co("Microsoft", "microsoft.com", "USA",
        sector="Cloud / AI / Enterprise", stage="Public", category="faang",
        tech="Python, Azure, Fabric, Synapse, Databricks, C#",
        reason="Azure AI platform and Fabric data stack — EU offices in Dublin, Munich, Stockholm",
        visa="yes", remote="Hybrid", scale="100000+"),
    _co("Apple", "apple.com", "USA",
        sector="AI / Hardware / Consumer", stage="Public", category="faang",
        tech="Python, Swift, CoreML, on-device ML",
        reason="Massive AI/Siri/privacy ML teams — EU offices in Cork, Amsterdam, Munich",
        visa="yes", remote="Mostly Office", scale="100000+"),
    _co("Netflix", "netflix.com", "USA",
        sector="Streaming / AI / Data", stage="Public", category="big tech",
        tech="Python, Spark, Kafka, Flink, Metaflow, Ray",
        reason="Known for world-class data platform engineering — offices in Amsterdam, LA",
        visa="yes", remote="Hybrid", scale="10000+"),
    _co("Nvidia", "nvidia.com", "USA",
        sector="AI Hardware / GPU / Deep Learning", stage="Public", category="big tech",
        tech="CUDA, Python, PyTorch, TensorRT, Triton",
        reason="The AI infrastructure company — data/ML engineers needed across Munich, Tel Aviv, Santa Clara",
        visa="yes", remote="Hybrid", scale="30000+"),
    _co("Salesforce", "salesforce.com", "USA",
        sector="CRM / AI / Cloud", stage="Public", category="big tech",
        tech="Python, Apex, Einstein AI, Tableau, MuleSoft",
        reason="Einstein AI and Data Cloud require large data engineering teams — Dublin, London, Paris offices",
        visa="yes", remote="Hybrid", scale="70000+"),
    _co("Oracle", "oracle.com", "USA",
        sector="Cloud / Database / ERP", stage="Public", category="big tech",
        tech="SQL, Python, Java, OCI, Oracle DB, Autonomous Data Warehouse",
        reason="Oracle Cloud Infra expanding rapidly — EU data centres in Amsterdam, Frankfurt, Madrid",
        visa="yes", remote="Hybrid", scale="100000+"),
    _co("IBM", "ibm.com", "USA",
        sector="AI / Cloud / Consulting", stage="Public", category="big tech",
        tech="Python, Watson, watsonx, OpenShift, DB2, Spark",
        reason="watsonx AI platform + Consulting practice — massive EU presence across Germany, France, India",
        visa="yes", remote="Hybrid", scale="100000+"),
    _co("Intel", "intel.com", "USA",
        sector="AI Hardware / Chip Design", stage="Public", category="big tech",
        tech="Python, C++, oneAPI, OpenVINO, Gaudi AI accelerator",
        reason="AI silicon and software stack — R&D offices in Munich, Haifa, Bangalore, Gdansk",
        visa="yes", remote="Hybrid", scale="100000+"),
    _co("Cisco", "cisco.com", "USA",
        sector="Networking / Security / AI", stage="Public", category="big tech",
        tech="Python, Go, Kafka, Spark, ThousandEyes, Splunk",
        reason="Network intelligence and security AI — Bangalore, Amsterdam, Berlin offices",
        visa="yes", remote="Hybrid", scale="80000+"),
    _co("Adobe", "adobe.com", "USA",
        sector="Creative AI / SaaS / Data", stage="Public", category="big tech",
        tech="Python, Spark, Kafka, ML, Real-time CDP, Firefly",
        reason="Adobe Experience Platform is a major data engineering product — Munich, Bucharest offices",
        visa="yes", remote="Hybrid", scale="30000+"),
    _co("Workday", "workday.com", "USA",
        sector="HR Tech / Finance / AI", stage="Public", category="big tech",
        tech="Python, Prism Analytics, Kafka, JAPE, Java",
        reason="HCM + Finance cloud — Dublin EMEA HQ, Amsterdam office",
        visa="yes", remote="Hybrid", scale="20000+"),
    _co("ServiceNow", "servicenow.com", "USA",
        sector="Enterprise AI / IT Service Mgmt", stage="Public", category="big tech",
        tech="Python, Now Platform, ML, NLP, JavaScript",
        reason="Now Intelligence AI platform — Amsterdam, Staines UK, Frankfurt offices",
        visa="yes", remote="Hybrid", scale="20000+"),
    _co("Palo Alto Networks", "paloaltonetworks.com", "USA",
        sector="Cybersecurity / AI", stage="Public", category="big tech",
        tech="Python, ML, Cortex XSIAM, Prisma Cloud, Go",
        reason="AI-driven security platform — Amsterdam, Tel Aviv, Bangalore offices",
        visa="yes", remote="Hybrid", scale="15000+"),
    _co("CrowdStrike", "crowdstrike.com", "USA",
        sector="Cybersecurity / AI", stage="Public", category="big tech",
        tech="Python, Go, Falcon, NG-SIEM, Threat Intelligence",
        reason="Cloud-native security AI — Amsterdam, Bucharest, Bangalore offices",
        visa="yes", remote="Remote-friendly", scale="10000+"),
    _co("Cloudflare", "cloudflare.com", "USA",
        sector="Network / Edge / Security", stage="Public", category="big tech",
        tech="Rust, Go, Python, Workers AI, Durable Objects, ClickHouse",
        reason="Edge computing and AI inference — Amsterdam, Lisbon, Austin offices; strong remote culture",
        visa="yes", remote="Yes", scale="5000+"),
    _co("Snowflake", "snowflake.com", "USA",
        sector="Data Cloud / AI", stage="Public", category="data platform",
        tech="SQL, Python, Snowpark, Cortex AI, dbt",
        reason="The data cloud — data engineers are their target customer AND internal staff; Amsterdam, Munich offices",
        visa="yes", remote="Hybrid", scale="7000+"),
    _co("Databricks", "databricks.com", "USA",
        sector="Data / AI / Lakehouse", stage="Late-stage private", category="data platform",
        tech="Python, Spark, Delta Lake, MLflow, Unity Catalog, SQL",
        reason="The lakehouse company — core product is what you build on; Amsterdam, London offices",
        visa="yes", remote="Hybrid", scale="7000+"),
    _co("Stripe", "stripe.com", "USA",
        sector="Payments / Fintech / AI", stage="Late-stage private", category="fintech",
        tech="Ruby, Java, Go, Python, ML, Scala",
        reason="Payments infrastructure + ML fraud models — Dublin EMEA HQ, Singapore offices",
        visa="yes", remote="Hybrid", scale="10000+"),
    _co("Uber", "uber.com", "USA",
        sector="Transport / AI / Platform", stage="Public", category="big tech",
        tech="Python, Go, Java, Kafka, Flink, Michelangelo ML",
        reason="World-class data platform (Presto, Kafka, Michelangelo) — Amsterdam, India offices",
        visa="yes", remote="Hybrid", scale="30000+"),
    _co("Airbnb", "airbnb.com", "USA",
        sector="Travel / AI / Platform", stage="Public", category="big tech",
        tech="Python, Spark, Presto, Airflow, dbt, PyTorch",
        reason="Strong open-source data tooling (Airflow, Superset) — remote-friendly after COVID shift",
        visa="yes", remote="Yes", scale="7000+"),
    _co("PayPal", "paypal.com", "USA",
        sector="Payments / AI / Fraud", stage="Public", category="fintech",
        tech="Python, Java, Spark, ML, Graph Neural Networks",
        reason="AI/ML fraud detection at scale — Dublin, Bangalore, Scottsdale offices",
        visa="yes", remote="Hybrid", scale="30000+"),
    _co("Palantir", "palantir.com", "USA",
        sector="AI / Government / Enterprise", stage="Public", category="data platform",
        tech="Java, Python, TypeScript, Foundry, AIP, Gotham",
        reason="Data integration platform for enterprises and governments — London, Munich offices",
        visa="yes", remote="Office-first", scale="4000+"),
    _co("Splunk", "splunk.com", "USA",
        sector="Data / Security / Observability", stage="Public (Cisco acquired)", category="big tech",
        tech="Python, SPL, ML, Kafka, SOAR",
        reason="Observability and security data platform — Dublin, London offices",
        visa="yes", remote="Hybrid", scale="8000+"),
    _co("Elastic", "elastic.co", "USA",
        sector="Search / Observability / AI", stage="Public", category="data platform",
        tech="Java, Python, Elasticsearch, Kibana, ML, ELSER",
        reason="Open-source search + Elasticsearch AI — fully distributed company with EU presence",
        visa="yes", remote="Yes", scale="3000+"),
    _co("MongoDB", "mongodb.com", "USA",
        sector="Database / AI / Cloud", stage="Public", category="data platform",
        tech="Python, JavaScript, Atlas Vector Search, Spark Connector",
        reason="Document database leader — Dublin, Warsaw, Amsterdam offices",
        visa="yes", remote="Hybrid", scale="5000+"),
    _co("Datadog", "datadoghq.com", "USA",
        sector="Observability / AI / Cloud Monitoring", stage="Public", category="data platform",
        tech="Go, Python, Kafka, Flink, ML",
        reason="Cloud monitoring leader — Paris HQ (founded in France!), Dublin, Boston offices",
        visa="yes", remote="Hybrid", scale="6000+"),
    _co("Twilio", "twilio.com", "USA",
        sector="CPaaS / Data / Customer Engagement", stage="Public", category="big tech",
        tech="Python, Go, Kafka, Segment CDP, dbt",
        reason="Segment CDP + communications platform — Dublin, Munich offices",
        visa="yes", remote="Yes", scale="8000+"),
    _co("GitHub", "github.com", "USA",
        sector="DevTools / AI / Platform", stage="Public (Microsoft)", category="big tech",
        tech="Ruby, Go, Python, Copilot AI, TypeScript",
        reason="Copilot AI product requires ML infrastructure — remote-first culture globally",
        visa="yes", remote="Yes", scale="4000+"),
    _co("GitLab", "gitlab.com", "USA",
        sector="DevTools / AI / Platform", stage="Public", category="big tech",
        tech="Ruby, Go, Python, GitLab AI, ClickHouse, dbt",
        reason="Fully remote company — data platform team, ClickHouse analytics, GitLab Duo AI",
        visa="yes", remote="Yes", scale="2500+"),
    _co("Coinbase", "coinbase.com", "USA",
        sector="Crypto / Fintech / Data", stage="Public", category="fintech",
        tech="Python, Go, Spark, dbt, Snowflake",
        reason="Crypto exchange with sophisticated data and ML — Dublin EU entity, remote roles",
        visa="yes", remote="Yes", scale="4000+"),
    _co("DoorDash", "doordash.com", "USA",
        sector="Delivery / AI / Logistics", stage="Public", category="big tech",
        tech="Python, Kotlin, Go, Flink, Snowflake, ML",
        reason="Logistics optimization and ML — data engineering is central to operations",
        visa="yes", remote="Hybrid", scale="8000+"),
    _co("Robinhood", "robinhood.com", "USA",
        sector="Fintech / Trading / AI", stage="Public", category="fintech",
        tech="Python, Go, Kafka, Flink, dbt",
        reason="Trading platform expanding globally — data engineering for market data pipelines",
        visa="yes", remote="Hybrid", scale="3000+"),
]

# ─────────────────────────────────────────────────────────────
#  US AI / DATA / MLOPS SPECIALISTS  (30 companies)
# ─────────────────────────────────────────────────────────────
US_AI_DATA = [
    _co("OpenAI", "openai.com", "USA",
        sector="AI / LLM / Research", stage="Late-stage private", category="ai specialist",
        tech="Python, PyTorch, CUDA, Kubernetes, TypeScript",
        reason="The LLM company — data engineering and ML infra are mission-critical roles",
        visa="yes", remote="Office-first", scale="2000+"),
    _co("Anthropic", "anthropic.com", "USA",
        sector="AI Safety / LLM", stage="Late-stage private", category="ai specialist",
        tech="Python, PyTorch, JAX, RLHF, Constitutional AI",
        reason="AI safety company building Claude — ML infra and data engineering key to training",
        visa="yes", remote="Hybrid", scale="1000+"),
    _co("Cohere", "cohere.com", "USA",
        sector="Enterprise AI / LLM", stage="Series C", category="ai specialist",
        tech="Python, PyTorch, RAG, fine-tuning, enterprise APIs",
        reason="Enterprise LLM platform — Toronto and London offices, EU expansion ongoing",
        visa="yes", remote="Yes", scale="500+"),
    _co("Scale AI", "scale.com", "USA",
        sector="AI Data / RLHF / Labelling", stage="Late-stage private", category="ai specialist",
        tech="Python, ML, data pipelines, annotation systems",
        reason="AI data company behind RLHF pipelines for major LLMs — data engineering core role",
        visa="yes", remote="Hybrid", scale="1000+"),
    _co("Weights & Biases", "wandb.ai", "USA",
        sector="MLOps / Experiment Tracking", stage="Series C", category="mlops",
        tech="Python, PyTorch, TensorFlow, MLflow, Go",
        reason="The MLOps experiment tracking leader — used by AI teams at every tier",
        visa="yes", remote="Yes", scale="500+"),
    _co("Hugging Face", "huggingface.co", "USA",
        sector="Open Source AI / LLM / Datasets", stage="Series D", category="ai specialist",
        tech="Python, PyTorch, Transformers, Datasets, Diffusers",
        reason="The GitHub of AI — hub for models and datasets, Paris-origin company with global team",
        visa="yes", remote="Yes", scale="500+"),
    _co("dbt Labs", "getdbt.com", "USA",
        sector="Data Transformation / Analytics Engineering", stage="Series D", category="data platform",
        tech="SQL, Python, dbt, Jinja, Semantic Layer",
        reason="The analytics engineering company — the tool you probably already use",
        visa="yes", remote="Yes", scale="500+"),
    _co("Airbyte", "airbyte.com", "USA",
        sector="Data Integration / ETL", stage="Series B", category="data platform",
        tech="Python, Java, dbt, Airbyte Platform, Docker",
        reason="Open-source ETL platform — remote-first, EU-friendly hiring",
        visa="yes", remote="Yes", scale="300+"),
    _co("Fivetran", "fivetran.com", "USA",
        sector="Data Integration / ELT", stage="Late-stage private", category="data platform",
        tech="Python, Java, SQL, Fivetran Platform, dbt",
        reason="ELT leader — Denver HQ but remote-friendly, India office in Bangalore",
        visa="yes", remote="Yes", scale="2000+"),
    _co("Monte Carlo", "montecarlodata.com", "USA",
        sector="Data Quality / Observability", stage="Series D", category="data platform",
        tech="Python, SQL, dbt, Airflow, Snowflake, BigQuery",
        reason="Data observability leader — data engineers are their target user and internal staff",
        visa="yes", remote="Yes", scale="300+"),
    _co("Atlan", "atlan.com", "USA",
        sector="Data Catalog / Governance", stage="Series C", category="data platform",
        tech="Python, Java, Elasticsearch, Kafka, dbt, Lineage",
        reason="Modern data catalog — Singapore-origin, fully remote, strong EU hiring",
        visa="yes", remote="Yes", scale="500+"),
    _co("Alation", "alation.com", "USA",
        sector="Data Catalog / Governance", stage="Late-stage private", category="data platform",
        tech="Python, Django, React, ML, Elasticsearch",
        reason="Data catalog and governance — Redwood City HQ, EU and India hiring",
        visa="yes", remote="Hybrid", scale="500+"),
    _co("Informatica", "informatica.com", "USA",
        sector="Data Integration / Cloud / MDM", stage="Public", category="data platform",
        tech="Python, CLAIRE AI, Informatica IDMC, Spark, Kafka",
        reason="Data integration giant — Hyderabad, Bangalore, Amsterdam offices",
        visa="yes", remote="Hybrid", scale="5000+"),
    _co("Alteryx", "alteryx.com", "USA",
        sector="Data Analytics / AI", stage="Public", category="data platform",
        tech="Python, R, Alteryx Platform, Spark, ML",
        reason="Analytics automation platform — London, Munich offices",
        visa="yes", remote="Hybrid", scale="3000+"),
    _co("Dataiku", "dataiku.com", "USA",
        sector="AI / Data Science Platform", stage="Late-stage private", category="data platform",
        tech="Python, R, Spark, dbt, MLflow, scikit-learn",
        reason="Enterprise AI platform — Paris-founded, US HQ, EU offices remain strong",
        visa="yes", remote="Hybrid", scale="1000+"),
    _co("H2O.ai", "h2o.ai", "USA",
        sector="AutoML / Enterprise AI", stage="Late-stage private", category="ai specialist",
        tech="Python, Java, H2O AutoML, LLM Studio, Wave",
        reason="Open-source AutoML platform — Mountain View HQ, remote-friendly",
        visa="yes", remote="Yes", scale="500+"),
    _co("DataRobot", "datarobot.com", "USA",
        sector="AutoML / MLOps / Enterprise AI", stage="Late-stage private", category="mlops",
        tech="Python, AutoML, MLOps, Generative AI, APIs",
        reason="Enterprise AI automation — remote-first, EU offices",
        visa="yes", remote="Yes", scale="1000+"),
    _co("Domino Data Lab", "dominodatalab.com", "USA",
        sector="MLOps / Data Science Platform", stage="Series E", category="mlops",
        tech="Python, R, Spark, Kubernetes, MLflow",
        reason="Enterprise ML platform for regulated industries — strong EU banking sector clients",
        visa="yes", remote="Yes", scale="500+"),
    _co("Collibra", "collibra.com", "Belgium",
        sector="Data Governance / Catalog", stage="Late-stage private", category="data platform",
        tech="Java, Python, Collibra Platform, GraphQL",
        reason="Belgian-founded data governance leader — Brussels HQ, EU Blue Card eligible",
        visa="yes", remote="Hybrid", scale="1000+"),
    _co("Pinecone", "pinecone.io", "USA",
        sector="Vector Database / AI", stage="Series C", category="ai specialist",
        tech="Python, Rust, vector embeddings, RAG architectures",
        reason="Vector database for AI apps — remote-first, fast-growing",
        visa="yes", remote="Yes", scale="300+"),
    _co("Weaviate", "weaviate.io", "Netherlands",
        sector="Vector Database / AI / Open Source", stage="Series C", category="ai specialist",
        tech="Go, Python, GraphQL, vector embeddings, RAG",
        reason="Amsterdam-founded vector DB — EU Blue Card eligible, remote-first culture",
        visa="yes", remote="Yes", scale="200+"),
    _co("Qdrant", "qdrant.tech", "Germany",
        sector="Vector Database / AI", stage="Series A", category="ai specialist",
        tech="Rust, Python, vector search, RAG, gRPC",
        reason="Berlin-based vector DB — EU Blue Card eligible, ML engineers needed",
        visa="yes", remote="Yes", scale="100+"),
    _co("LangChain", "langchain.com", "USA",
        sector="AI / LLM Tooling / Open Source", stage="Series A", category="ai specialist",
        tech="Python, LangChain, LangSmith, LangGraph, vector stores",
        reason="The LLM orchestration framework — data engineers needed for LangSmith tracing infra",
        visa="yes", remote="Yes", scale="100+"),
    _co("Mixpanel", "mixpanel.com", "USA",
        sector="Product Analytics / Data", stage="Late-stage private", category="data platform",
        tech="Python, Kafka, ClickHouse, dbt, Presto",
        reason="Product analytics leader — Singapore, Barcelona offices",
        visa="yes", remote="Yes", scale="500+"),
    _co("Amplitude", "amplitude.com", "USA",
        sector="Product Analytics / AI", stage="Public", category="data platform",
        tech="Python, Kafka, ClickHouse, dbt, Redshift",
        reason="Digital analytics platform — EU customers, Amsterdam office",
        visa="yes", remote="Hybrid", scale="700+"),
    _co("Segment", "segment.com", "USA",
        sector="Customer Data Platform / AI", stage="Public (Twilio)", category="data platform",
        tech="Go, Node.js, Kafka, Redshift, dbt, ML",
        reason="CDP backbone for thousands of companies — Twilio/Segment merged, remote roles available",
        visa="yes", remote="Yes", scale="500+"),
    _co("Grafana Labs", "grafana.com", "USA",
        sector="Observability / Monitoring / Open Source", stage="Late-stage private", category="data platform",
        tech="Go, Python, Prometheus, Loki, Tempo, ClickHouse",
        reason="Grafana OSS — fully remote company, EU-heavy team, data infra roles",
        visa="yes", remote="Yes", scale="1000+"),
    _co("ClickHouse", "clickhouse.com", "USA",
        sector="OLAP Database / AI", stage="Series B", category="data platform",
        tech="C++, SQL, ClickHouse, columnar storage, Python",
        reason="Open-source OLAP DB becoming the analytics standard — remote-first, EU team",
        visa="yes", remote="Yes", scale="500+"),
    _co("Astronomer", "astronomer.io", "USA",
        sector="MLOps / Airflow / Data Orchestration", stage="Series C", category="mlops",
        tech="Python, Apache Airflow, Astro, dbt, Kubernetes",
        reason="Airflow-as-a-service — data pipeline engineers are their product users AND employees",
        visa="yes", remote="Yes", scale="500+"),
    _co("Prefect", "prefect.io", "USA",
        sector="Data Orchestration / MLOps", stage="Series C", category="mlops",
        tech="Python, Prefect, Kubernetes, Docker, dbt",
        reason="Modern data orchestration — remote-first, competing with Airflow",
        visa="yes", remote="Yes", scale="200+"),
]

# ─────────────────────────────────────────────────────────────
#  EU MNCS — GERMANY, NETHERLANDS, SWEDEN  (25 companies)
# ─────────────────────────────────────────────────────────────
EU_MNCS = [
    # Germany
    _co("SAP", "sap.com", "Germany",
        sector="Enterprise Software / AI / ERP", stage="Public", category="eu mnc",
        tech="ABAP, Python, SAP HANA, BTP, AI Core, Datasphere",
        reason="Walldorf HQ — global leader in enterprise software, massive data engineering teams",
        visa="yes", remote="Hybrid", scale="100000+"),
    _co("Siemens", "siemens.com", "Germany",
        sector="Industrial AI / IoT / Infrastructure", stage="Public", category="eu mnc",
        tech="Python, MindSphere, AI, Digital Twin, IIoT",
        reason="Industrial AI and digital twin platform — Munich HQ, Hyderabad India office",
        visa="yes", remote="Hybrid", scale="300000+"),
    _co("Bosch", "bosch.com", "Germany",
        sector="Industrial AI / Automotive / IoT", stage="Private", category="eu mnc",
        tech="Python, C++, AI, Computer Vision, Edge AI, ROS",
        reason="AI-first manufacturing giant — Stuttgart HQ, Hyderabad engineering center",
        visa="yes", remote="Hybrid", scale="400000+"),
    _co("BMW Group", "bmwgroup.com", "Germany",
        sector="Automotive AI / Data", stage="Public", category="eu mnc",
        tech="Python, Azure, Databricks, ML, Computer Vision",
        reason="AI-driven mobility — Munich HQ, BMW AI Cloud uses Databricks + Azure",
        visa="yes", remote="Hybrid", scale="150000+"),
    _co("Mercedes-Benz Group", "mercedes-benz.com", "Germany",
        sector="Automotive AI / Data Platform", stage="Public", category="eu mnc",
        tech="Python, AWS, Spark, ML, Data Lake, MBUX AI",
        reason="Automotive data platform — Stuttgart HQ, strong ML for autonomous driving",
        visa="yes", remote="Hybrid", scale="150000+"),
    _co("Zalando", "zalando.com", "Germany",
        sector="E-Commerce / AI / Fashion Tech", stage="Public", category="eu tech",
        tech="Python, Kafka, Flink, Spark, Go, dbt, ML",
        reason="Europe's largest online fashion platform — Berlin HQ, English working language",
        visa="yes", remote="Hybrid", scale="15000+"),
    _co("Delivery Hero", "deliveryhero.com", "Germany",
        sector="Food Delivery / AI / Logistics", stage="Public", category="eu tech",
        tech="Python, Kotlin, Go, Kafka, Flink, dbt, Redshift",
        reason="Global food delivery platform — Berlin HQ, English-only working language, 50+ countries",
        visa="yes", remote="Hybrid", scale="40000+"),
    _co("HelloFresh", "hellofresh.com", "Germany",
        sector="Food Tech / AI / Supply Chain", stage="Public", category="eu tech",
        tech="Python, Airflow, dbt, BigQuery, ML, Tableau",
        reason="Meal kit + data company — Berlin HQ, English working language, demand forecasting ML",
        visa="yes", remote="Hybrid", scale="20000+"),
    _co("N26", "n26.com", "Germany",
        sector="Neobank / Fintech / AI", stage="Late-stage private", category="eu fintech",
        tech="Python, Kafka, Scala, ML, Fraud Detection AI, PostgreSQL",
        reason="EU neobank — Berlin HQ, ML fraud models, EU banking license = strong EU presence",
        visa="yes", remote="Hybrid", scale="3000+"),
    _co("Celonis", "celonis.com", "Germany",
        sector="Process Mining / AI / Enterprise", stage="Late-stage private", category="eu tech",
        tech="Python, SQL, PQL, ML, Process Mining, SAP integration",
        reason="Process mining AI leader — Munich HQ, NY office, EU Blue Card eligible",
        visa="yes", remote="Hybrid", scale="3000+"),
    # Netherlands
    _co("ASML", "asml.com", "Netherlands",
        sector="Semiconductor / AI / High-Tech", stage="Public", category="eu mnc",
        tech="Python, C++, ML, data analytics, computer vision",
        reason="World's most critical chip manufacturer — Eindhoven HQ, no AI team is too small for ASML",
        visa="yes", remote="Mostly Office", scale="40000+"),
    _co("Philips", "philips.com", "Netherlands",
        sector="HealthTech / AI / Medical", stage="Public", category="eu mnc",
        tech="Python, TensorFlow, DICOM, HealthSuite, Azure AI",
        reason="Health AI — Amsterdam HQ, medical imaging ML, India R&D center in Bangalore",
        visa="yes", remote="Hybrid", scale="70000+"),
    _co("Booking.com", "booking.com", "Netherlands",
        sector="Travel / AI / Platform", stage="Public (Booking Holdings)", category="eu tech",
        tech="Python, Java, Kafka, Hadoop, ML, A/B testing platform",
        reason="Amsterdam HQ — massive A/B testing and ML infrastructure, data engineers central",
        visa="yes", remote="Hybrid", scale="20000+"),
    _co("Adyen", "adyen.com", "Netherlands",
        sector="Payments / Fintech / AI", stage="Public", category="eu fintech",
        tech="Java, Python, Go, Kafka, ML, fraud detection",
        reason="Dutch payments giant — Amsterdam HQ, EU Blue Card eligible, fintech data engineering",
        visa="yes", remote="Hybrid", scale="4000+"),
    _co("ING", "ing.com", "Netherlands",
        sector="Banking / AI / Data", stage="Public", category="eu mnc",
        tech="Python, Spark, Kafka, ML, Azure, dbt",
        reason="EU bank and tech innovator — ING Tech in Amsterdam, Bucharest, Manila",
        visa="yes", remote="Hybrid", scale="60000+"),
    _co("TomTom", "tomtom.com", "Netherlands",
        sector="Geospatial / AI / Maps", stage="Public", category="eu tech",
        tech="Python, C++, ML, geospatial data, real-time map processing",
        reason="Maps + geospatial AI — Amsterdam HQ, data engineering for HD maps and navigation",
        visa="yes", remote="Hybrid", scale="4000+"),
    _co("Shell", "shell.com", "Netherlands",
        sector="Energy / AI / Data Platform", stage="Public", category="eu mnc",
        tech="Python, Azure, ML, IoT, digital twins, energy AI",
        reason="Shell AI division — The Hague HQ, massive energy data platform engineering teams",
        visa="yes", remote="Hybrid", scale="80000+"),
    # Sweden / Nordics
    _co("Spotify", "spotify.com", "Sweden",
        sector="Music / AI / Audio", stage="Public", category="eu tech",
        tech="Python, Java, Kafka, Flink, Hadoop, Luigi, Beam",
        reason="Stockholm HQ — creator of Luigi/Beam patterns, podcast AI, recommendation ML",
        visa="yes", remote="Yes", scale="9000+"),
    _co("Klarna", "klarna.com", "Sweden",
        sector="Fintech / BNPL / AI", stage="Late-stage private", category="eu fintech",
        tech="Python, Kotlin, Kafka, ML, fraud AI, dbt",
        reason="Stockholm HQ — AI-first bank, GenAI integration into product, EU Blue Card eligible",
        visa="yes", remote="Hybrid", scale="5000+"),
    _co("Ericsson", "ericsson.com", "Sweden",
        sector="Telecom / AI / 5G", stage="Public", category="eu mnc",
        tech="Python, C++, Java, ML, network AI, 5G data analytics",
        reason="Stockholm HQ — 5G network intelligence and AI, massive global data teams",
        visa="yes", remote="Hybrid", scale="100000+"),
    _co("Northvolt", "northvolt.com", "Sweden",
        sector="Battery Tech / AI / Manufacturing", stage="Late-stage private", category="eu tech",
        tech="Python, ML, IoT, manufacturing AI, digital twin",
        reason="Stockholm-based battery manufacturer using AI for production optimisation",
        visa="yes", remote="Mostly Office", scale="6000+"),
    _co("Volvo Cars", "volvocars.com", "Sweden",
        sector="Automotive AI / Safety / Data", stage="Public", category="eu mnc",
        tech="Python, Azure, ML, computer vision, autonomous driving AI",
        reason="Gothenburg HQ — full self-driving AI team, data platform for connected cars",
        visa="yes", remote="Hybrid", scale="45000+"),
    _co("Amadeus IT Group", "amadeus.com", "Spain",
        sector="Travel Tech / AI / Data", stage="Public", category="eu tech",
        tech="Python, Java, Spark, ML, Amadeus APIs, real-time processing",
        reason="Nice-based travel tech giant — Madrid development center, world's largest GDS",
        visa="yes", remote="Hybrid", scale="20000+"),
    _co("ABN AMRO", "abnamro.com", "Netherlands",
        sector="Banking / AI / Data", stage="Public", category="eu mnc",
        tech="Python, Spark, ML, Azure, dbt, Kafka",
        reason="Dutch bank with large AI and data team — Amsterdam HQ, EU Blue Card eligible",
        visa="yes", remote="Hybrid", scale="20000+"),
    _co("OVHcloud", "ovhcloud.com", "France",
        sector="Cloud / AI / Infrastructure", stage="Public", category="eu tech",
        tech="Python, OpenStack, Ceph, Kubernetes, bare metal AI",
        reason="Europe's largest cloud provider — Roubaix HQ, sovereign cloud for EU customers",
        visa="yes", remote="Hybrid", scale="3000+"),
]

# ─────────────────────────────────────────────────────────────
#  EU TECH LEADERS BY COUNTRY  (35 companies)
# ─────────────────────────────────────────────────────────────
EU_TECH = [
    # Ireland — major US tech EMEA bases
    _co("Intercom", "intercom.com", "Ireland",
        sector="Customer Support AI / SaaS", stage="Late-stage private", category="eu tech",
        tech="Ruby, React, ML, Fin AI agent, Elixir",
        reason="Dublin HQ — AI-first customer support, EU Blue Card eligible",
        visa="yes", remote="Hybrid", scale="1000+"),
    _co("Stripe Ireland", "stripe.com/ie", "Ireland",
        sector="Payments / Fintech / AI", stage="Late-stage private", category="eu fintech",
        tech="Ruby, Go, Python, ML, Scala, Kotlin",
        reason="Dublin is Stripe's EMEA HQ — EU Blue Card, strong hiring",
        visa="yes", remote="Hybrid", scale="2000+"),
    _co("HubSpot", "hubspot.com", "Ireland",
        sector="CRM / AI / Marketing", stage="Public", category="eu tech",
        tech="Python, Java, Kafka, ML, Spark, dbt",
        reason="Dublin EMEA HQ — strong engineering culture, AI features expanding",
        visa="yes", remote="Hybrid", scale="7000+"),
    # France
    _co("Criteo", "criteo.com", "France",
        sector="AdTech / AI / Data", stage="Public", category="eu tech",
        tech="Python, Spark, Kafka, ML, Scala, real-time bidding",
        reason="Paris HQ — massive real-time ML for advertising, data engineers central",
        visa="yes", remote="Hybrid", scale="4000+"),
    _co("Doctolib", "doctolib.eu", "France",
        sector="HealthTech / AI / SaaS", stage="Late-stage private", category="eu tech",
        tech="Ruby, Python, ML, PostgreSQL, AI triage, scheduling AI",
        reason="Europe's largest health platform — Paris HQ, AI for healthcare data",
        visa="yes", remote="Hybrid", scale="3000+"),
    _co("BlaBlaCar", "blablacar.com", "France",
        sector="Transport / AI / Marketplace", stage="Late-stage private", category="eu tech",
        tech="PHP, Python, ML, Go, recommendation systems",
        reason="Paris HQ — ride-sharing ML and data platform",
        visa="yes", remote="Hybrid", scale="800+"),
    _co("Contentsquare", "contentsquare.com", "France",
        sector="Digital Experience / AI / Analytics", stage="Late-stage private", category="eu tech",
        tech="Python, Spark, ML, Kafka, ClickHouse",
        reason="Paris-based experience analytics — raised $1.4B, strong data engineering team",
        visa="yes", remote="Hybrid", scale="2000+"),
    _co("Mirakl", "mirakl.com", "France",
        sector="Marketplace / E-Commerce / AI", stage="Late-stage private", category="eu tech",
        tech="Java, Python, ML, Kafka, PostgreSQL",
        reason="B2B marketplace platform — Paris HQ, powers Carrefour, Decathlon marketplaces",
        visa="yes", remote="Hybrid", scale="800+"),
    # Poland
    _co("Allegro", "allegro.eu", "Poland",
        sector="E-Commerce / AI / Platform", stage="Public", category="eu tech",
        tech="Java, Python, Kafka, Spark, ML, Kubernetes",
        reason="Poland's largest e-commerce — Warsaw HQ, massive data engineering and ML platform",
        visa="yes", remote="Hybrid", scale="5000+"),
    _co("Docplanner", "docplanner.com", "Poland",
        sector="HealthTech / AI / SaaS", stage="Late-stage private", category="eu tech",
        tech="Python, PHP, ML, PostgreSQL, Kafka",
        reason="Warsaw HQ — largest medical appointment platform in Europe, AI triage ML",
        visa="yes", remote="Hybrid", scale="3000+"),
    # Romania
    _co("UiPath", "uipath.com", "Romania",
        sector="RPA / AI / Automation", stage="Public", category="eu tech",
        tech="Python, .NET, ML, Computer Vision, RPA, NLP",
        reason="Bucharest-origin automation giant — EU Blue Card, Bucharest + Timisoara offices",
        visa="yes", remote="Hybrid", scale="4000+"),
    _co("Bitdefender", "bitdefender.com", "Romania",
        sector="Cybersecurity / AI / ML", stage="Late-stage private", category="eu tech",
        tech="Python, C++, ML, threat intelligence, antivirus AI",
        reason="Bucharest HQ — AI-driven cybersecurity, EU Blue Card eligible",
        visa="yes", remote="Hybrid", scale="1800+"),
    # Czech Republic / Slovakia
    _co("JetBrains", "jetbrains.com", "Czech Republic",
        sector="DevTools / AI / IDE", stage="Private", category="eu tech",
        tech="Kotlin, Java, Python, AI coding assistant, Qodana",
        reason="Prague HQ — AI code completion, Grazie AI — EU Blue Card eligible",
        visa="yes", remote="Hybrid", scale="2000+"),
    _co("Avast (Gen Digital)", "gendigital.com", "Czech Republic",
        sector="Cybersecurity / AI / Privacy", stage="Public", category="eu tech",
        tech="C++, Python, ML, threat detection AI",
        reason="Prague-based security company, now Gen Digital — EU Blue Card eligible",
        visa="yes", remote="Hybrid", scale="2500+"),
    # Estonia / Baltics
    _co("Pipedrive", "pipedrive.com", "Estonia",
        sector="CRM / AI / SaaS", stage="Late-stage private", category="eu tech",
        tech="PHP, Go, Python, ML, AI CRM features",
        reason="Tallinn HQ — EU startup success story, AI features in CRM, Blue Card eligible",
        visa="yes", remote="Yes", scale="1000+"),
    _co("Bolt", "bolt.eu", "Estonia",
        sector="Mobility / AI / Super App", stage="Late-stage private", category="eu tech",
        tech="Python, Go, Kotlin, Flink, ML, Kubernetes",
        reason="Tallinn HQ — ride-hailing and delivery in 45 countries, massive data platform",
        visa="yes", remote="Hybrid", scale="8000+"),
    _co("Wise", "wise.com", "Estonia",
        sector="Fintech / Payments / AI", stage="Public", category="eu fintech",
        tech="Python, Java, Kafka, ML, fraud AI, Scala",
        reason="Tallinn-founded, London-listed — EU Blue Card eligible, international money transfer",
        visa="yes", remote="Hybrid", scale="4000+"),
    # Belgium
    _co("Showpad", "showpad.com", "Belgium",
        sector="Sales Enablement / AI / SaaS", stage="Late-stage private", category="eu tech",
        tech="Python, Node.js, ML, NLP, React",
        reason="Ghent HQ — AI sales coaching, EU Blue Card eligible",
        visa="yes", remote="Hybrid", scale="500+"),
    # Switzerland
    _co("Logitech", "logitech.com", "Switzerland",
        sector="Hardware / AI / Video Collaboration", stage="Public", category="eu mnc",
        tech="Python, C++, ML, computer vision, CV AI",
        reason="Lausanne HQ — AI-enhanced peripherals, AI team expanding",
        visa="yes", remote="Hybrid", scale="8000+"),
    # Portugal
    _co("Feedzai", "feedzai.com", "Portugal",
        sector="Fintech / AI / Fraud Detection", stage="Late-stage private", category="eu fintech",
        tech="Java, Python, Spark, ML, real-time fraud AI",
        reason="Coimbra/Lisbon HQ — AI fraud detection for banks, EU Blue Card eligible",
        visa="yes", remote="Hybrid", scale="600+"),
    _co("Talkdesk", "talkdesk.com", "Portugal",
        sector="Contact Centre AI / SaaS", stage="Late-stage private", category="eu tech",
        tech="Python, Java, Kafka, ML, NLP, real-time AI",
        reason="Lisbon HQ — AI-first contact centre, EU Blue Card eligible, $10B valuation",
        visa="yes", remote="Hybrid", scale="2000+"),
    _co("Outsystems", "outsystems.com", "Portugal",
        sector="Low-Code / AI / Platform", stage="Late-stage private", category="eu tech",
        tech="Java, .NET, AI code generation, ML, platform engineering",
        reason="Lisbon HQ — low-code platform with AI capabilities, EU Blue Card eligible",
        visa="yes", remote="Hybrid", scale="2000+"),
    # Spain
    _co("Glovo", "glovoapp.com", "Spain",
        sector="Food Delivery / AI / Logistics", stage="Late-stage private (Delivery Hero)", category="eu tech",
        tech="Python, Kotlin, Go, ML, operations research, Kafka",
        reason="Barcelona HQ — logistics AI and route optimization, EU Blue Card eligible",
        visa="yes", remote="Hybrid", scale="3000+"),
    _co("Typeform", "typeform.com", "Spain",
        sector="SaaS / AI / Forms", stage="Late-stage private", category="eu tech",
        tech="Node.js, Python, ML, React, PostgreSQL",
        reason="Barcelona HQ — AI form intelligence, EU Blue Card eligible",
        visa="yes", remote="Yes", scale="500+"),
    _co("Factorial HR", "factorialhr.com", "Spain",
        sector="HR Tech / AI / SaaS", stage="Series D", category="eu tech",
        tech="Ruby, Python, ML, PostgreSQL, Kafka",
        reason="Barcelona HQ — AI-driven HR platform, EU Blue Card eligible, Spanish unicorn",
        visa="yes", remote="Hybrid", scale="1000+"),
    # Italy
    _co("Bending Spoons", "bendingspoons.com", "Italy",
        sector="Mobile / AI / SaaS", stage="Late-stage private", category="eu tech",
        tech="Swift, Kotlin, Python, ML, A/B testing platform",
        reason="Milan HQ — owns Evernote, Splice, WeTransfer; data engineering central; EU Blue Card",
        visa="yes", remote="Office-first", scale="500+"),
    # Luxembourg
    _co("Skyscanner", "skyscanner.net", "Luxembourg",
        sector="Travel / AI / Price Comparison", stage="Public (Trip.com)", category="eu tech",
        tech="Python, Kafka, Spark, ML, pricing AI",
        reason="Edinburgh + Barcelona engineering — EU Blue Card, ML for travel pricing",
        visa="yes", remote="Yes", scale="1500+"),
    # Denmark
    _co("Zendesk Copenhagen", "zendesk.com", "Denmark",
        sector="Customer Support AI / CRM", stage="Private (acquired)", category="eu tech",
        tech="Python, Ruby, ML, NLP, AI agents, Kafka",
        reason="Copenhagen + Dublin offices — AI-first support platform, EU Blue Card",
        visa="yes", remote="Hybrid", scale="6000+"),
    # Finland
    _co("Nokia", "nokia.com", "Finland",
        sector="Telecom / AI / 5G", stage="Public", category="eu mnc",
        tech="Python, C++, Java, ML, 5G network AI, Digital Operations",
        reason="Espoo HQ — network AI and 5G data analytics, India R&D center",
        visa="yes", remote="Hybrid", scale="80000+"),
    _co("Wolt", "wolt.com", "Finland",
        sector="Food Delivery / AI / Logistics", stage="Late-stage private (DoorDash)", category="eu tech",
        tech="Python, Kotlin, Go, ML, Kafka, operations research",
        reason="Helsinki HQ — 27-country food delivery, logistics AI, EU Blue Card eligible",
        visa="yes", remote="Hybrid", scale="8000+"),
    # Norway
    _co("Kahoot", "kahoot.com", "Norway",
        sector="EdTech / AI / Learning Platform", stage="Public", category="eu tech",
        tech="Node.js, Python, ML, React, real-time platform",
        reason="Oslo HQ — learning AI, EU Blue Card eligible",
        visa="yes", remote="Hybrid", scale="500+"),
    _co("Visma", "visma.com", "Norway",
        sector="Enterprise Software / AI / Cloud", stage="Late-stage private", category="eu mnc",
        tech="Java, Python, .NET, ML, cloud-first ERP, SaaS",
        reason="Oslo HQ — Nordics' largest software company, data engineering across 100+ products",
        visa="yes", remote="Hybrid", scale="15000+"),
    # Greece
    _co("Workable", "workable.com", "Greece",
        sector="HR Tech / AI / ATS", stage="Late-stage private", category="eu tech",
        tech="Ruby, Python, ML, NLP, React, PostgreSQL",
        reason="Athens HQ — AI-first ATS, EU Blue Card eligible, strong engineering culture",
        visa="yes", remote="Yes", scale="500+"),
]

# ─────────────────────────────────────────────────────────────
#  INDIA — TOP TECH EMPLOYERS  (45 companies)
# ─────────────────────────────────────────────────────────────
INDIA_EMPLOYERS = [
    # Services / MNCs
    _co("Tata Consultancy Services", "tcs.com", "India",
        sector="IT Services / AI / Cloud", stage="Public", category="india mnc",
        tech="Python, Java, Spark, Azure, AWS, ML",
        reason="World's 2nd largest IT services company — Hyderabad, Mumbai, Chennai offices",
        visa="Unknown", lang="English", remote="Hybrid", scale="600000+"),
    _co("Infosys", "infosys.com", "India",
        sector="IT Services / AI / Consulting", stage="Public", category="india mnc",
        tech="Python, Java, Spark, Azure, AWS, dbt",
        reason="Bangalore HQ — AI lab, data engineering practices, Hyderabad campus",
        visa="Unknown", lang="English", remote="Hybrid", scale="300000+"),
    _co("Wipro", "wipro.com", "India",
        sector="IT Services / AI / Cloud", stage="Public", category="india mnc",
        tech="Python, Java, Spark, AI, Azure, GCP",
        reason="Bangalore HQ — AI and analytics practice, Hyderabad engineering center",
        visa="Unknown", lang="English", remote="Hybrid", scale="250000+"),
    _co("HCL Technologies", "hcltech.com", "India",
        sector="IT Services / Cloud / AI", stage="Public", category="india mnc",
        tech="Python, Java, Spark, SAP, AI studio",
        reason="Noida HQ — strong data engineering and cloud practices, Hyderabad offices",
        visa="Unknown", lang="English", remote="Hybrid", scale="220000+"),
    _co("Tech Mahindra", "techmahindra.com", "India",
        sector="IT Services / AI / Telecom", stage="Public", category="india mnc",
        tech="Python, Java, ML, 5G AI, data platforms",
        reason="Pune HQ — Mahindra Group, strong AI and data engineering services",
        visa="Unknown", lang="English", remote="Hybrid", scale="150000+"),
    _co("LTIMindtree", "ltimindtree.com", "India",
        sector="IT Services / Data / AI", stage="Public", category="india mnc",
        tech="Python, Spark, Azure, Databricks, ML, dbt",
        reason="Mumbai HQ — merger of L&T Infotech + Mindtree, strong data engineering practice",
        visa="Unknown", lang="English", remote="Hybrid", scale="80000+"),
    _co("Mphasis", "mphasis.com", "India",
        sector="IT Services / AI / Banking Tech", stage="Public", category="india mnc",
        tech="Python, Java, ML, cloud platforms, AI",
        reason="Bangalore HQ — deep banking AI, HP origin, Hyderabad development center",
        visa="Unknown", lang="English", remote="Hybrid", scale="35000+"),
    _co("Persistent Systems", "persistent.com", "India",
        sector="Software Engineering / AI / Products", stage="Public", category="india mnc",
        tech="Python, Java, Spark, ML, GenAI, cloud",
        reason="Pune HQ — strong engineering culture, AI + data engineering practices",
        visa="Unknown", lang="English", remote="Hybrid", scale="23000+"),
    _co("Hexaware Technologies", "hexaware.com", "India",
        sector="IT Services / Cloud / AI", stage="Private", category="india mnc",
        tech="Python, Java, ML, Azure, AWS, automation AI",
        reason="Mumbai HQ — cloud-first services, Hyderabad engineering",
        visa="Unknown", lang="English", remote="Hybrid", scale="30000+"),
    _co("Coforge", "coforge.com", "India",
        sector="IT Services / AI / Travel Tech", stage="Public", category="india mnc",
        tech="Python, Java, Spark, ML, travel domain AI",
        reason="Noida HQ — strong BFS + travel sector data engineering",
        visa="Unknown", lang="English", remote="Hybrid", scale="25000+"),
    # Product companies / Unicorns
    _co("Zoho Corporation", "zoho.com", "India",
        sector="SaaS / CRM / AI / Business Software", stage="Private", category="india product",
        tech="Python, Java, ML, Zia AI, Zoho Analytics, in-house infra",
        reason="Chennai HQ — builds everything in-house, data engineering is core, 100M+ users",
        visa="Unknown", lang="English", remote="Hybrid", scale="15000+"),
    _co("Freshworks", "freshworks.com", "India",
        sector="CRM / SaaS / AI", stage="Public", category="india product",
        tech="Ruby, Python, ML, Freddy AI, Kafka, PostgreSQL",
        reason="Chennai-founded, NASDAQ-listed — AI CRM, data engineering, Hyderabad office",
        visa="Unknown", lang="English", remote="Hybrid", scale="7000+"),
    _co("Flipkart", "flipkart.com", "India",
        sector="E-Commerce / AI / Logistics", stage="Private (Walmart)", category="india product",
        tech="Java, Python, Spark, Flink, ML, Kafka, Hadoop",
        reason="Bangalore HQ — India's Amazon, world-class data platform engineering team",
        visa="Unknown", lang="English", remote="Hybrid", scale="50000+"),
    _co("Swiggy", "swiggy.com", "India",
        sector="Food Delivery / AI / Logistics", stage="Public", category="india product",
        tech="Python, Go, Java, Kafka, ML, Flink, operations research",
        reason="Bangalore HQ — food delivery + quick commerce, logistics ML at scale",
        visa="Unknown", lang="English", remote="Hybrid", scale="7000+"),
    _co("Zomato", "zomato.com", "India",
        sector="Food Delivery / AI / Platform", stage="Public", category="india product",
        tech="Python, Go, Kafka, ML, real-time ML, Gurgaon HQ",
        reason="Gurgaon HQ — food + Blinkit quick commerce, data platform engineering at scale",
        visa="Unknown", lang="English", remote="Hybrid", scale="6000+"),
    _co("PhonePe", "phonepe.com", "India",
        sector="Fintech / Payments / AI", stage="Late-stage private", category="india fintech",
        tech="Java, Python, Kafka, ML, fraud AI, real-time pipelines",
        reason="Bangalore HQ — India's largest payments platform (UPI), data engineering critical",
        visa="Unknown", lang="English", remote="Hybrid", scale="4000+"),
    _co("Razorpay", "razorpay.com", "India",
        sector="Fintech / Payments / API", stage="Late-stage private", category="india fintech",
        tech="Java, Go, Python, ML, fraud AI, PostgreSQL, Kafka",
        reason="Bangalore HQ — payments API platform, ML for fraud and risk",
        visa="Unknown", lang="English", remote="Hybrid", scale="3000+"),
    _co("CRED", "cred.club", "India",
        sector="Fintech / AI / Credit", stage="Late-stage private", category="india fintech",
        tech="Python, Go, Kafka, ML, data engineering",
        reason="Bangalore HQ — credit card payments platform, strong data engineering culture",
        visa="Unknown", lang="English", remote="Hybrid", scale="1500+"),
    _co("Meesho", "meesho.com", "India",
        sector="Social Commerce / AI / E-Commerce", stage="Late-stage private", category="india product",
        tech="Python, Go, Java, Spark, ML, Kafka, recommendation AI",
        reason="Bangalore HQ — social commerce at scale, ML for recommendations and pricing",
        visa="Unknown", lang="English", remote="Hybrid", scale="3000+"),
    _co("Zepto", "zeptonow.com", "India",
        sector="Quick Commerce / AI / Logistics", stage="Late-stage private", category="india product",
        tech="Python, Go, ML, real-time optimisation, Kafka",
        reason="Mumbai HQ — 10-minute delivery, logistics ML and demand forecasting",
        visa="Unknown", lang="English", remote="Hybrid", scale="2000+"),
    _co("Groww", "groww.in", "India",
        sector="Fintech / Investment / AI", stage="Late-stage private", category="india fintech",
        tech="Java, Python, Go, Kafka, ML, data pipelines",
        reason="Bangalore HQ — retail investment platform, data engineering for financial analytics",
        visa="Unknown", lang="English", remote="Hybrid", scale="2000+"),
    _co("Postman", "postman.com", "India",
        sector="DevTools / API / SaaS", stage="Late-stage private", category="india product",
        tech="Node.js, Python, ML, API intelligence, Go",
        reason="Bangalore HQ, SF HQ — API platform used by 30M developers, data engineering central",
        visa="Unknown", lang="English", remote="Yes", scale="1000+"),
    _co("BrowserStack", "browserstack.com", "India",
        sector="DevTools / Testing / SaaS", stage="Late-stage private", category="india product",
        tech="Node.js, Python, ML, real-time test infra, Kafka",
        reason="Mumbai HQ — test automation platform, data engineering for test analytics",
        visa="Unknown", lang="English", remote="Yes", scale="1500+"),
    _co("Darwinbox", "darwinbox.com", "India",
        sector="HR Tech / AI / SaaS", stage="Series D", category="india product",
        tech="Python, ML, NLP, Django, PostgreSQL, AI-driven HR",
        reason="Hyderabad HQ — HR platform unicorn, AI analytics, home turf advantage",
        visa="Unknown", lang="English", remote="Hybrid", scale="1000+"),
    _co("Druva", "druva.com", "India",
        sector="Cloud Data Protection / AI", stage="Late-stage private", category="india product",
        tech="Python, Go, AWS, ML, Spark, data protection AI",
        reason="Pune + Santa Clara HQ — cloud backup AI, data engineering for global resilience",
        visa="Unknown", lang="English", remote="Yes", scale="2000+"),
    _co("ShareChat", "sharechat.com", "India",
        sector="Social Media / AI / Video", stage="Late-stage private", category="india product",
        tech="Python, Go, Java, ML, RecSys, video AI, Kafka",
        reason="Bangalore HQ — India's largest regional social platform, heavy ML for content",
        visa="Unknown", lang="English", remote="Hybrid", scale="2000+"),
    _co("Juspay", "juspay.in", "India",
        sector="Fintech / Payments / AI", stage="Series C", category="india fintech",
        tech="Haskell, Purescript, Python, ML, payments AI",
        reason="Bangalore HQ — payments infrastructure for India's largest banks and apps",
        visa="Unknown", lang="English", remote="Yes", scale="500+"),
    _co("Hasura", "hasura.io", "India",
        sector="API / Data Access / Open Source", stage="Series C", category="india product",
        tech="Haskell, Go, GraphQL, PostgreSQL, data federation",
        reason="Bangalore HQ — instant APIs on data layer, developer tools with strong data engineering",
        visa="Unknown", lang="English", remote="Yes", scale="300+"),

    # ── GCCs (Global Capability Centers) — Hyderabad / Bangalore ──────
    _co("Microsoft IDC", "microsoft.com/en-in", "India",
        sector="Cloud / AI / Enterprise", stage="Public", category="india gcc",
        tech="Azure, Python, C#, ML, Copilot, Fabric, Synapse",
        reason="Hyderabad HQ — Microsoft's largest R&D centre outside USA; Azure Data, Fabric, AI teams based here",
        visa="yes", lang="English", remote="Hybrid", scale="15000+"),
    _co("Goldman Sachs India", "goldmansachs.com", "India",
        sector="Fintech / Data Platform / AI", stage="Public", category="india gcc",
        tech="Python, Java, Slang, Kafka, Spark, GS data platform",
        reason="Hyderabad / Bangalore — engineering hub for GS data platform, ML risk models, quantitative analytics",
        visa="yes", lang="English", remote="Hybrid", scale="10000+"),
    _co("JP Morgan Chase India", "jpmorgan.com", "India",
        sector="Fintech / AI / Data Engineering", stage="Public", category="india gcc",
        tech="Python, Spark, Athena, Kafka, ML, cloud data",
        reason="Hyderabad / Bangalore / Mumbai — large data engineering teams, AI/ML for banking, Athena platform",
        visa="yes", lang="English", remote="Hybrid", scale="50000+"),
    _co("Walmart Global Tech India", "tech.walmart.com", "India",
        sector="Retail Tech / Data Platform / AI", stage="Public", category="india gcc",
        tech="Python, Spark, Kafka, Hadoop, ML, real-time analytics",
        reason="Bangalore HQ — largest tech hub outside USA; supply chain AI, data platform, real-time analytics",
        visa="yes", lang="English", remote="Hybrid", scale="15000+"),
    _co("Uber India", "uber.com/in", "India",
        sector="Mobility / AI / Data Platform", stage="Public", category="india gcc",
        tech="Python, Go, Spark, Flink, ML, geospatial, Michelangelo",
        reason="Hyderabad / Bangalore — data science, ML platform (Michelangelo), routing AI, real-time systems",
        visa="yes", lang="English", remote="Hybrid", scale="5000+"),
    _co("LinkedIn India", "linkedin.com", "India",
        sector="Social / Data / AI / Recruitment", stage="Public (MSFT)", category="india gcc",
        tech="Python, Java, Kafka, Spark, ML, Pinot, Samza",
        reason="Bangalore — LinkedIn's engineering centre; feed ranking, talent AI, data infra (Pinot, Samza)",
        visa="yes", lang="English", remote="Hybrid", scale="3000+"),
    _co("Adobe India", "adobe.com", "India",
        sector="Creative Tech / Data / AI", stage="Public", category="india gcc",
        tech="Python, Spark, ML, Firefly AI, AEM, data analytics",
        reason="Noida / Bangalore — Firefly AI, Experience Cloud data engineering, ML for creative products",
        visa="yes", lang="English", remote="Hybrid", scale="8000+"),
    _co("Salesforce India", "salesforce.com", "India",
        sector="CRM / AI / Data Platform", stage="Public", category="india gcc",
        tech="Apex, Python, Java, Tableau, Einstein AI, data cloud",
        reason="Hyderabad / Bangalore — Einstein AI, Slack platform, Tableau engineering teams",
        visa="yes", lang="English", remote="Hybrid", scale="10000+"),
    _co("Qualcomm India", "qualcomm.com", "India",
        sector="Semiconductor / AI / Edge ML", stage="Public", category="india gcc",
        tech="C++, Python, TensorFlow, on-device AI, DSP, NPU",
        reason="Hyderabad HQ — largest R&D centre outside USA; on-device AI, ML compiler, edge inference",
        visa="yes", lang="English", remote="Hybrid", scale="17000+"),
    _co("PayPal India", "paypal.com", "India",
        sector="Fintech / Fraud AI / Data", stage="Public", category="india gcc",
        tech="Python, Java, Spark, ML, fraud detection, real-time data",
        reason="Chennai / Bangalore — fraud detection ML, risk data platform, payment analytics",
        visa="yes", lang="English", remote="Hybrid", scale="4000+"),

    # ── Data / Analytics / AI Consultancies ────────────────────────────
    _co("Fractal Analytics", "fractal.ai", "India",
        sector="AI / Analytics / Decision Science", stage="Unicorn", category="india data",
        tech="Python, R, Spark, TensorFlow, ML, causal AI, NLP",
        reason="Mumbai / Bangalore / Hyderabad — pure-play AI/analytics for Fortune 500; strong data engineering and ML practice",
        visa="yes", lang="English", remote="Hybrid", scale="5000+"),
    _co("Tiger Analytics", "tigeranalytics.com", "India",
        sector="AI / Data Engineering / Analytics", stage="Growth", category="india data",
        tech="Python, Spark, dbt, Snowflake, ML, Databricks",
        reason="Chennai / Bangalore — data engineering + ML for Fortune 500; Databricks and dbt-heavy stack matches yours",
        visa="yes", lang="English", remote="Yes", scale="3000+"),
    _co("LatentView Analytics", "latentview.com", "India",
        sector="Data Analytics / Business Intelligence", stage="Public", category="india data",
        tech="Python, SQL, Spark, ML, Tableau, Power BI",
        reason="Chennai / Global — listed data analytics firm; digital analytics, data engineering for global clients",
        visa="yes", lang="English", remote="Hybrid", scale="3000+"),
    _co("Mu Sigma", "mu-sigma.com", "India",
        sector="Decision Science / Analytics / AI", stage="Private", category="india data",
        tech="Python, R, Spark, ML, muPDT, data engineering",
        reason="Bangalore HQ — world's largest pure-play analytics firm; decision science for Fortune 500",
        visa="yes", lang="English", remote="Hybrid", scale="5000+"),
    _co("ThoughtWorks India", "thoughtworks.com", "India",
        sector="Tech Consulting / Data / AI", stage="Public", category="india tech",
        tech="Python, Java, Spark, ML, cloud data, data mesh",
        reason="Bangalore / Hyderabad — data mesh pioneers, AI consulting, strong engineering culture",
        visa="yes", lang="English", remote="Yes", scale="12000+"),
    _co("The Math Company (MathCo)", "themathcompany.com", "India",
        sector="AI / Data Engineering / Decision Science", stage="Series B", category="india data",
        tech="Python, Spark, Databricks, ML, NLP, dbt",
        reason="Bangalore HQ — AI and data engineering for Fortune 500; Databricks + dbt stack, strong data platform practice",
        visa="yes", lang="English", remote="Hybrid", scale="1500+"),
    _co("Sigmoid", "sigmoid.com", "India",
        sector="Data Engineering / AI / Cloud", stage="Series B", category="india data",
        tech="Python, Spark, dbt, Databricks, Airflow, ML, Kafka",
        reason="Bangalore HQ — pure-play data engineering consultancy; Databricks partner, dbt shop",
        visa="yes", lang="English", remote="Yes", scale="800+"),
    _co("Quantiphi", "quantiphi.com", "India",
        sector="AI / Data / ML Engineering", stage="Growth", category="india data",
        tech="Python, GCP, Vertex AI, ML, NLP, Databricks",
        reason="Mumbai / Bangalore — Google Cloud Premier Partner; AI/ML engineering, Vertex AI specialisation",
        visa="yes", lang="English", remote="Yes", scale="3000+"),

    # ── Indian Product Companies (AI/Data focus) ───────────────────────
    _co("Sarvam AI", "sarvam.ai", "India",
        sector="AI / LLM / Indic Languages", stage="Series A", category="india ai",
        tech="Python, PyTorch, LLM, ASR, TTS, Indic NLP",
        reason="Bangalore — building India-first LLMs; state-of-the-art speech and language AI",
        visa="Unknown", lang="English", remote="Yes", scale="100+"),
    _co("Krutrim (Ola AI)", "krutrim.com", "India",
        sector="AI / LLM / Infrastructure", stage="Unicorn", category="india ai",
        tech="Python, PyTorch, LLM, AI chips, inference infra",
        reason="Bangalore — Ola's AI subsidiary; India's first AI unicorn, building LLMs and AI chips",
        visa="Unknown", lang="English", remote="Hybrid", scale="500+"),
    _co("Nykaa", "nykaa.com", "India",
        sector="E-Commerce / Data / AI", stage="Public", category="india product",
        tech="Python, Spark, ML, recommendation AI, Airflow",
        reason="Mumbai / Bangalore — data engineering for beauty e-commerce; recommendation AI, ML platform",
        visa="Unknown", lang="English", remote="Hybrid", scale="3000+"),
    _co("Delhivery", "delhivery.com", "India",
        sector="Logistics / Supply Chain AI / Data", stage="Public", category="india product",
        tech="Python, Spark, Kafka, ML, routing AI, supply chain analytics",
        reason="Gurugram HQ — data engineering for India's largest logistics network; routing AI, real-time tracking",
        visa="Unknown", lang="English", remote="Hybrid", scale="8000+"),
    _co("Cars24", "cars24.com", "India",
        sector="Automotive / AI / Data Platform", stage="Unicorn", category="india product",
        tech="Python, Spark, ML, pricing AI, Databricks",
        reason="Gurugram — AI-driven used car pricing; data platform, ML for valuation and demand forecasting",
        visa="Unknown", lang="English", remote="Hybrid", scale="2000+"),
    _co("Urban Company", "urbancompany.com", "India",
        sector="Marketplace / AI / Operations", stage="Unicorn", category="india product",
        tech="Python, ML, Spark, demand forecasting, geospatial AI",
        reason="Gurugram — AI for demand forecasting, worker matching, pricing optimisation",
        visa="Unknown", lang="English", remote="Hybrid", scale="3000+"),
]

# ─────────────────────────────────────────────────────────────
#  JAPAN — TOP TECH EMPLOYERS  (20 companies)
# ─────────────────────────────────────────────────────────────
JAPAN_EMPLOYERS = [
    _co("Sony Corporation", "sony.com", "Japan",
        sector="AI / Gaming / Entertainment Tech", stage="Public", category="japan big tech",
        tech="Python, C++, ML, computer vision, PlayStation AI",
        reason="Tokyo HQ — AI research labs, gaming AI (PlayStation), robotics AI",
        visa="yes", lang="Japanese (Learning)", remote="Hybrid", scale="110000+"),
    _co("Toyota Motor", "toyota.com", "Japan",
        sector="Automotive AI / Robotics / Data", stage="Public", category="japan big tech",
        tech="Python, C++, ML, autonomous driving AI, digital twin",
        reason="Toyota City / Tokyo — Woven City AI, TRI (Toyota Research Institute), massive data platform",
        visa="yes", lang="Japanese (Learning)", remote="Mostly Office", scale="360000+"),
    _co("Rakuten Group", "rakuten.com", "Japan",
        sector="E-Commerce / Fintech / AI", stage="Public", category="japan big tech",
        tech="Python, Java, Scala, Spark, ML, recommendation AI",
        reason="English is Rakuten's official internal language — uniquely accessible for non-Japanese speakers; diverse international team in Tokyo, strong data engineering hiring",
        visa="yes", lang="English", remote="Hybrid", scale="30000+"),
    _co("NTT Data", "nttdata.com", "Japan",
        sector="IT Services / AI / Cloud", stage="Public", category="japan big tech",
        tech="Python, Java, Spark, Azure, ML, cloud AI",
        reason="Tokyo HQ — one of Japan's largest IT companies, global data engineering projects",
        visa="yes", lang="Japanese (Learning)", remote="Hybrid", scale="160000+"),
    _co("SoftBank", "softbank.jp", "Japan",
        sector="Telecom / AI / Venture", stage="Public", category="japan big tech",
        tech="Python, ML, 5G AI, Vision Fund tech portfolio",
        reason="Tokyo HQ — massive AI investment thesis, 5G data analytics platform",
        visa="yes", lang="Japanese (Learning)", remote="Hybrid", scale="55000+"),
    _co("Fujitsu", "fujitsu.com", "Japan",
        sector="Enterprise IT / AI / Quantum", stage="Public", category="japan big tech",
        tech="Python, Java, AI Zinrai platform, quantum computing, Fugaku",
        reason="Tokyo HQ — AI Zinrai platform, quantum computing + AI research labs",
        visa="yes", lang="Japanese (Learning)", remote="Hybrid", scale="130000+"),
    _co("Hitachi", "hitachi.com", "Japan",
        sector="Industrial AI / IoT / Infrastructure", stage="Public", category="japan big tech",
        tech="Python, Java, ML, Lumada IoT, digital twin, edge AI",
        reason="Tokyo HQ — Lumada AI platform for industrial data, strong AI division",
        visa="yes", lang="Japanese (Learning)", remote="Hybrid", scale="320000+"),
    _co("NEC Corporation", "nec.com", "Japan",
        sector="AI / Biometrics / Government Tech", stage="Public", category="japan big tech",
        tech="Python, C++, ML, face recognition AI, NEC AI",
        reason="Tokyo HQ — world's best face recognition AI, biometric data platform",
        visa="yes", lang="Japanese (Learning)", remote="Hybrid", scale="110000+"),
    _co("Mercari", "mercari.com", "Japan",
        sector="Marketplace / AI / Fintech", stage="Public", category="japan tech",
        tech="Python, Go, Kotlin, ML, Spark, Kubernetes, recommendation AI",
        reason="Tokyo HQ — English-friendly startup culture, strong ML for marketplace AI",
        visa="yes", lang="English", remote="Yes", scale="3000+"),
    _co("CyberAgent", "cyberagent.co.jp", "Japan",
        sector="Media / AI / Gaming / AdTech", stage="Public", category="japan tech",
        tech="Python, Kotlin, Go, ML, AbemaTV AI, ad auction ML",
        reason="Tokyo HQ — AI Lab doing NLP research, AbemaTV streaming AI, game AI",
        visa="yes", lang="Japanese (Learning)", remote="Hybrid", scale="7000+"),
    _co("DeNA Co", "dena.com", "Japan",
        sector="Gaming / AI / Healthcare", stage="Public", category="japan tech",
        tech="Python, C++, ML, game AI, AI healthcare diagnostics",
        reason="Tokyo HQ — gaming + AI healthcare, English-accessible engineering teams",
        visa="yes", lang="Japanese (Learning)", remote="Hybrid", scale="3000+"),
    _co("Recruit Holdings", "recruit.co.jp", "Japan",
        sector="HR Tech / AI / Marketplace", stage="Public", category="japan big tech",
        tech="Python, Java, ML, NLP, Rikunabi job AI, Indeed-owner",
        reason="Tokyo HQ — owns Indeed globally! Data platform for job matching ML",
        visa="yes", lang="Japanese (Learning)", remote="Hybrid", scale="50000+"),
    _co("Sansan", "sansan.com", "Japan",
        sector="B2B SaaS / AI / Business Cards", stage="Public", category="japan tech",
        tech="Python, ML, OCR AI, NLP, contact intelligence",
        reason="Tokyo HQ — AI-powered B2B networking, English-friendly engineering",
        visa="yes", lang="English", remote="Hybrid", scale="1500+"),
    _co("Freee K.K.", "freee.co.jp", "Japan",
        sector="Fintech / Cloud Accounting / AI", stage="Public", category="japan tech",
        tech="Ruby, Python, ML, accounting AI, cloud infrastructure",
        reason="Tokyo HQ — cloud accounting for SMBs, AI financial automation",
        visa="yes", lang="Japanese (Learning)", remote="Yes", scale="2000+"),
    _co("Money Forward", "moneyforward.com", "Japan",
        sector="Fintech / AI / Personal Finance", stage="Public", category="japan tech",
        tech="Ruby, Python, ML, financial AI, cloud",
        reason="Tokyo HQ — personal finance + B2B fintech AI, Osaka office too",
        visa="yes", lang="Japanese (Learning)", remote="Hybrid", scale="1500+"),
    _co("SmartNews", "smartnews.com", "Japan",
        sector="Media / AI / News Recommendation", stage="Late-stage private", category="japan tech",
        tech="Python, Go, ML, NLP, recommendation AI, news personalisation",
        reason="Tokyo + San Francisco HQ — English-accessible team, heavy ML for news AI",
        visa="yes", lang="English", remote="Hybrid", scale="500+"),
    _co("Visional Inc.", "visional.inc", "Japan",
        sector="HR Tech / AI / Recruitment", stage="Public", category="japan tech",
        tech="Python, PHP, ML, NLP, job matching AI, BizReach",
        reason="Tokyo HQ — Japan's largest executive recruiting platform, job matching ML",
        visa="yes", lang="Japanese (Learning)", remote="Hybrid", scale="2000+"),
    _co("LINE (LY Corporation)", "lycorp.co.jp", "Japan",
        sector="Messaging / AI / Fintech", stage="Public (SoftBank+Naver)", category="japan big tech",
        tech="Python, Go, Java, Spark, ML, NLP, LINE messaging AI",
        reason="Tokyo HQ — dominant messaging app in Japan + SE Asia, AI + data platform large team",
        visa="yes", lang="Japanese (Learning)", remote="Hybrid", scale="10000+"),
    _co("Panasonic Holdings", "panasonic.com", "Japan",
        sector="Manufacturing AI / IoT / Energy", stage="Public", category="japan big tech",
        tech="Python, C++, ML, IoT, energy AI, Yosemite AI platform",
        reason="Osaka HQ — industrial AI, connected factory, AI for energy management",
        visa="yes", lang="Japanese (Learning)", remote="Hybrid", scale="240000+"),
    _co("Keyence Corporation", "keyence.com", "Japan",
        sector="Industrial Automation / AI / Sensors", stage="Public", category="japan big tech",
        tech="C++, Python, computer vision, ML, precision sensors",
        reason="Osaka HQ — Japan's most profitable tech company, industrial AI and sensor data",
        visa="yes", lang="Japanese (Learning)", remote="Mostly Office", scale="10000+"),
]

# ─────────────────────────────────────────────────────────────
#  AUSTRALIA / NEW ZEALAND  (25 companies)
# ─────────────────────────────────────────────────────────────
AU_NZ_EMPLOYERS = [
    _co("Atlassian", "atlassian.com", "Australia",
        sector="DevTools / AI / SaaS", stage="Public", category="australia tech",
        tech="Python, Java, Kotlin, Loom AI, Jira AI, Spark, dbt",
        reason="Sydney HQ + San Francisco — Jira, Confluence, Rovo AI; fully remote-capable culture",
        visa="yes", lang="English", remote="Yes", scale="12000+"),
    _co("Canva", "canva.com", "Australia",
        sector="Creative AI / Design / SaaS", stage="Late-stage private", category="australia tech",
        tech="Python, Java, Go, ML, computer vision, Magic AI, Kafka",
        reason="Sydney HQ — $26B valuation, AI design tools, massive data engineering team",
        visa="yes", lang="English", remote="Hybrid", scale="5000+"),
    _co("Xero", "xero.com", "New Zealand",
        sector="Fintech / Cloud Accounting / AI", stage="Public", category="nz tech",
        tech="Python, .NET, ML, Spark, dbt, cloud accounting AI",
        reason="Wellington HQ + Melbourne — accounting platform for SMBs, AI financial insights",
        visa="yes", lang="English", remote="Hybrid", scale="5000+"),
    _co("WiseTech Global", "wisetechglobal.com", "Australia",
        sector="Logistics Tech / AI / Supply Chain", stage="Public", category="australia tech",
        tech="Python, Java, ML, CargoWise platform, data engineering",
        reason="Sydney HQ — global logistics software, CargoWise AI, strong data platform team",
        visa="yes", lang="English", remote="Hybrid", scale="3000+"),
    _co("REA Group", "realestate.com.au", "Australia",
        sector="PropTech / AI / Data", stage="Public", category="australia tech",
        tech="Python, Scala, Spark, ML, Kafka, dbt, recommendation AI",
        reason="Melbourne HQ — Australia's largest property portal, data engineering is core",
        visa="yes", lang="English", remote="Hybrid", scale="3000+"),
    _co("SEEK", "seek.com.au", "Australia",
        sector="HR Tech / AI / Jobs Platform", stage="Public", category="australia tech",
        tech="Python, Java, ML, NLP, recommendation AI, Spark",
        reason="Melbourne HQ — Australasia's largest job board (owns this market), data ML central",
        visa="yes", lang="English", remote="Hybrid", scale="3000+"),
    _co("Afterpay (Block)", "block.xyz", "Australia",
        sector="Fintech / BNPL / AI", stage="Public", category="australia tech",
        tech="Python, Go, ML, fraud AI, Kotlin, dbt, Spark",
        reason="Melbourne + San Francisco — BNPL leader, Block ecosystem, strong ML team",
        visa="yes", lang="English", remote="Hybrid", scale="7000+"),
    _co("SafetyCulture", "safetyculture.com", "Australia",
        sector="Safety Tech / AI / SaaS", stage="Late-stage private", category="australia tech",
        tech="Python, Go, ML, Kafka, computer vision, React Native",
        reason="Sydney HQ — workplace safety AI, $1.7B valuation, data engineering team",
        visa="yes", lang="English", remote="Hybrid", scale="1000+"),
    _co("Culture Amp", "cultureamp.com", "Australia",
        sector="HR Tech / People Analytics / AI", stage="Late-stage private", category="australia tech",
        tech="Ruby, Python, ML, NLP, people analytics AI, dbt",
        reason="Melbourne HQ — people analytics and engagement AI, $1.5B valuation",
        visa="yes", lang="English", remote="Yes", scale="1000+"),
    _co("Airwallex", "airwallex.com", "Australia",
        sector="Fintech / Global Payments / AI", stage="Late-stage private", category="australia tech",
        tech="Java, Python, Go, Kafka, ML, fraud AI",
        reason="Melbourne HQ — global payments infrastructure, $5.5B valuation, strong data team",
        visa="yes", lang="English", remote="Hybrid", scale="2000+"),
    _co("Zip Co", "zip.co", "Australia",
        sector="Fintech / BNPL / AI", stage="Public", category="australia tech",
        tech="Python, Java, ML, fraud AI, dbt, Spark",
        reason="Sydney HQ — buy-now-pay-later, ML for credit risk and fraud detection",
        visa="yes", lang="English", remote="Hybrid", scale="1500+"),
    _co("Deputy", "deputy.com", "Australia",
        sector="HR Tech / Workforce Management / AI", stage="Late-stage private", category="australia tech",
        tech="PHP, Python, ML, scheduling AI, React",
        reason="Sydney HQ — workforce management AI, $500M+ valuation",
        visa="yes", lang="English", remote="Yes", scale="500+"),
    _co("Nearmap", "nearmap.com", "Australia",
        sector="Geospatial AI / Aerial Imagery / SaaS", stage="Private (Thoma Bravo)", category="australia tech",
        tech="Python, TensorFlow, computer vision, geospatial AI, cloud",
        reason="Sydney HQ — aerial imagery AI for construction, insurance; geospatial data engineering",
        visa="yes", lang="English", remote="Hybrid", scale="500+"),
    _co("Carsales", "carsales.com.au", "Australia",
        sector="Marketplace / AI / Automotive", stage="Public", category="australia tech",
        tech="Python, .NET, ML, recommendation AI, Kafka",
        reason="Melbourne HQ — largest auto marketplace in AU/NZ, data engineering for pricing AI",
        visa="yes", lang="English", remote="Hybrid", scale="2000+"),
    _co("Employment Hero", "employmenthero.com", "Australia",
        sector="HR Tech / AI / SMB SaaS", stage="Late-stage private", category="australia tech",
        tech="Ruby, Python, ML, AI HR assistant, PostgreSQL",
        reason="Sydney HQ — HR and payroll AI for SMBs, $2B valuation",
        visa="yes", lang="English", remote="Yes", scale="1000+"),
    _co("Domain Holdings", "domain.com.au", "Australia",
        sector="PropTech / AI / Data", stage="Public", category="australia tech",
        tech="Python, Scala, ML, property pricing AI, dbt",
        reason="Sydney HQ — REA Group competitor, property data and pricing AI",
        visa="yes", lang="English", remote="Hybrid", scale="1500+"),
    _co("Envato", "envato.com", "Australia",
        sector="Creative Marketplace / AI / Digital Assets", stage="Private", category="australia tech",
        tech="Ruby, Python, ML, recommendation AI, Kafka",
        reason="Melbourne HQ — creative digital marketplace (Themeforest), data engineering team",
        visa="yes", lang="English", remote="Yes", scale="600+"),
    _co("Data#3", "data3.com.au", "Australia",
        sector="IT Services / Cloud / AI", stage="Public", category="australia tech",
        tech="Python, Azure, AWS, ML, Power BI, data engineering services",
        reason="Brisbane HQ — leading IT services company in AU, data platform practice",
        visa="yes", lang="English", remote="Hybrid", scale="1500+"),
    _co("Brighte", "brighte.com.au", "Australia",
        sector="Fintech / Clean Energy / AI", stage="Series D", category="australia tech",
        tech="Python, Go, ML, credit AI, dbt, Kafka",
        reason="Sydney HQ — clean energy financing AI, fast-growing fintech",
        visa="yes", lang="English", remote="Hybrid", scale="300+"),
    _co("Airtasker", "airtasker.com", "Australia",
        sector="Gig Economy / AI / Marketplace", stage="Public", category="australia tech",
        tech="Ruby, Python, ML, trust and safety AI, PostgreSQL",
        reason="Sydney HQ — services marketplace with ML for matching and fraud",
        visa="yes", lang="English", remote="Hybrid", scale="300+"),
    _co("PaperKite", "paperkite.co.nz", "New Zealand",
        sector="Mobile / AI / Consulting", stage="Private", category="nz tech",
        tech="Swift, Kotlin, Python, ML, React Native",
        reason="Wellington HQ — NZ's top mobile and AI consultancy",
        visa="yes", lang="English", remote="Hybrid", scale="100+"),
    _co("Inde (formerly Vend)", "vendhq.com", "New Zealand",
        sector="Retail Tech / AI / POS", stage="Public (Lightspeed)", category="nz tech",
        tech="PHP, Python, ML, retail analytics AI, PostgreSQL",
        reason="Auckland origin — point-of-sale AI, now Lightspeed, NZ engineering team remains",
        visa="yes", lang="English", remote="Hybrid", scale="200+"),
    _co("Pacific Edge", "pacificedge.co.nz", "New Zealand",
        sector="Biotech / AI / Diagnostics", stage="Public", category="nz tech",
        tech="Python, ML, bioinformatics AI, bladder cancer diagnostics",
        reason="Dunedin HQ — AI diagnostics, clinical data engineering",
        visa="yes", lang="English", remote="Hybrid", scale="100+"),
    _co("Pushpay", "pushpay.com", "New Zealand",
        sector="Fintech / Faith Tech / AI", stage="Public", category="nz tech",
        tech="C#, Python, ML, payments AI, .NET",
        reason="Auckland HQ — donor management and payments AI for faith sector",
        visa="yes", lang="English", remote="Hybrid", scale="500+"),
    _co("Laybuy", "laybuy.com", "New Zealand",
        sector="Fintech / BNPL / AI", stage="Private", category="nz tech",
        tech="PHP, Python, ML, credit AI, fraud detection",
        reason="Auckland HQ — NZ's BNPL platform, credit risk ML engineering",
        visa="yes", lang="English", remote="Hybrid", scale="100+"),
]

# ─────────────────────────────────────────────────────────────
#  GLOBAL REMOTE-FIRST  (15 companies)
# ─────────────────────────────────────────────────────────────
GLOBAL_REMOTE = [
    _co("GitLab (remote)", "gitlab.com", "USA",
        sector="DevTools / AI / Platform", stage="Public", category="remote-first",
        tech="Ruby, Go, Python, ClickHouse, dbt, GitLab Duo AI",
        reason="ALL-REMOTE company — handbook-first culture, EU-friendly timezone, data engineering team",
        visa="yes", lang="English", remote="Yes", geo="Global", scale="2500+"),
    _co("Automattic", "automattic.com", "USA",
        sector="CMS / Open Source / AI", stage="Late-stage private", category="remote-first",
        tech="PHP, JavaScript, Python, ML, WordPress.com, Tumblr, Jetpack AI",
        reason="100% distributed — WordPress + Tumblr + WooCommerce, data engineering for 43% of the web",
        visa="yes", lang="English", remote="Yes", geo="Global", scale="2000+"),
    _co("Zapier", "zapier.com", "USA",
        sector="Automation / AI / No-Code", stage="Late-stage private", category="remote-first",
        tech="Python, Django, Celery, ML, AI Zaps, workflows",
        reason="Fully remote — workflow automation AI, data engineering for integration pipelines",
        visa="yes", lang="English", remote="Yes", geo="Global", scale="800+"),
    _co("InVision", "invisionapp.com", "USA",
        sector="Design / Collaboration / AI", stage="Late-stage private", category="remote-first",
        tech="Node.js, Go, Python, ML, React",
        reason="Fully remote — design collaboration platform, data engineering team",
        visa="yes", lang="English", remote="Yes", geo="Global", scale="500+"),
    _co("Remote.com", "remote.com", "Portugal",
        sector="EOR / HR Tech / Global Payroll", stage="Late-stage private", category="remote-first",
        tech="Elixir, Ruby, Python, ML, global HR AI",
        reason="The EOR platform — they enable global hiring of engineers like you; Lisbon HQ, fully remote",
        visa="yes", lang="English", remote="Yes", geo="Global", scale="1500+"),
    _co("Deel", "deel.com", "USA",
        sector="EOR / Global Payroll / AI", stage="Late-stage private", category="remote-first",
        tech="Node.js, Go, Python, ML, global payroll AI",
        reason="Global EOR leader — enables companies to hire you anywhere; data engineering at scale",
        visa="yes", lang="English", remote="Yes", geo="Global", scale="3000+"),
    _co("Doist", "doist.com", "Portugal",
        sector="Productivity / SaaS / AI", stage="Private", category="remote-first",
        tech="Python, Swift, Kotlin, ML, Todoist AI",
        reason="Fully remote — Todoist + Twist, data engineering for productivity analytics",
        visa="yes", lang="English", remote="Yes", geo="Global", scale="100+"),
    _co("Basecamp", "basecamp.com", "USA",
        sector="Project Management / SaaS", stage="Private", category="remote-first",
        tech="Ruby on Rails, JavaScript, ML, PostgreSQL",
        reason="Remote-first pioneer — data engineering for project management analytics",
        visa="yes", lang="English", remote="Yes", geo="Global", scale="60+"),
    _co("Toggl", "toggl.com", "Estonia",
        sector="Productivity / SaaS / AI", stage="Private", category="remote-first",
        tech="Go, TypeScript, Python, ML, time tracking AI",
        reason="Fully remote from Tallinn — time tracking + hiring AI, EU Blue Card eligible",
        visa="yes", lang="English", remote="Yes", geo="Global", scale="150+"),
    _co("Hotjar (by Contentsquare)", "hotjar.com", "Malta",
        sector="Product Analytics / AI / UX", stage="Public (Contentsquare)", category="remote-first",
        tech="Python, Go, ML, session recording AI, heatmap analytics",
        reason="Remote-first European analytics — Malta-founded, EU-friendly culture",
        visa="yes", lang="English", remote="Yes", geo="Global", scale="300+"),
    _co("Airtable", "airtable.com", "USA",
        sector="No-Code / AI / Database", stage="Late-stage private", category="remote-first",
        tech="Node.js, Python, ML, data engineering, Airtable AI",
        reason="No-code database platform with AI — data engineering for Airtable Intelligence",
        visa="yes", lang="English", remote="Hybrid", geo="USA / Global", scale="1500+"),
    _co("Miro", "miro.com", "Netherlands",
        sector="Collaboration / AI / Visual Work", stage="Late-stage private", category="remote-first",
        tech="Java, Go, Python, ML, Miro AI, Kubernetes",
        reason="Amsterdam HQ — online whiteboard with AI, EU Blue Card eligible, remote-friendly",
        visa="yes", lang="English", remote="Yes", geo="Global", scale="2000+"),
    _co("Loom (Atlassian)", "loom.com", "USA",
        sector="Video Messaging / AI / Async Work", stage="Public (Atlassian)", category="remote-first",
        tech="Python, React, ML, video AI, transcription AI",
        reason="Async video platform — Atlassian-owned, AI transcription and summaries",
        visa="yes", lang="English", remote="Yes", geo="Global", scale="500+"),
    _co("Notion", "notion.so", "USA",
        sector="Productivity / AI / No-Code", stage="Late-stage private", category="remote-first",
        tech="TypeScript, Python, ML, Notion AI, vector search",
        reason="Productivity platform with Notion AI — data engineers for AI features and analytics",
        visa="yes", lang="English", remote="Hybrid", geo="USA / Europe", scale="600+"),
    _co("Linear", "linear.app", "USA",
        sector="DevTools / Project Management / AI", stage="Series C", category="remote-first",
        tech="TypeScript, Go, Python, ML, Linear AI, Postgres",
        reason="Remote-first issue tracker — AI-enhanced project management, data engineering for analytics",
        visa="yes", lang="English", remote="Yes", geo="Global", scale="100+"),
]


# ─────────────────────────────────────────────────────────────
#  MAIN EXPORT
# ─────────────────────────────────────────────────────────────

def load_static_companies():
    """
    Return all static companies as a list of dicts matching FIELDS in schema.py.
    Deduped by company name (case-insensitive) before returning.
    """
    all_companies = (
        US_BIG_TECH +
        US_AI_DATA +
        EU_MNCS +
        EU_TECH +
        INDIA_EMPLOYERS +
        JAPAN_EMPLOYERS +
        AU_NZ_EMPLOYERS +
        GLOBAL_REMOTE
    )

    # Deduplicate by lowercase company name
    seen = set()
    unique = []
    for co in all_companies:
        key = co["Company"].lower().strip()
        if key not in seen:
            seen.add(key)
            unique.append(co)

    return unique


if __name__ == "__main__":
    companies = load_static_companies()
    by_country = {}
    for c in companies:
        country = c["Country"]
        by_country.setdefault(country, 0)
        by_country[country] += 1

    print(f"\nStatic company list: {len(companies)} total\n")
    print("By country:")
    for country, count in sorted(by_country.items(), key=lambda x: -x[1]):
        print(f"  {country:<25} {count}")
    print(f"\nSectors breakdown: {len(set(c['Sector'] for c in companies))} unique sectors")
    print(f"EU Blue Card eligible: {sum(1 for c in companies if c['Region_Eligibility'] == 'Eligible')}")
